export const ErrorLabels = {
  // Auth
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_GOOGLE_DOMAIN_NOT_ALLOWED: 'AUTH_GOOGLE_DOMAIN_NOT_ALLOWED',

  // Data
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  DATA_ALREADY_EXISTS: 'DATA_ALREADY_EXISTS',
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',

  // Academic
  ACADEMIC_YEAR_CONFLICT: 'ACADEMIC_YEAR_CONFLICT',
  ENROLLMENT_DUPLICATE: 'ENROLLMENT_DUPLICATE',
  ENROLLMENT_INVALID_STATUS: 'ENROLLMENT_INVALID_STATUS',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorLabel = (typeof ErrorLabels)[keyof typeof ErrorLabels];
